// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Trs.DataConsole;

namespace Trs.DataConsole.Migrations
{
    [DbContext(typeof(DataConsoleContext))]
    partial class DataConsoleContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.3-rtm-32065")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Trs.Data.Entities.Translation", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("BlockedBy");

                    b.Property<DateTime?>("BlockedTime");

                    b.Property<string>("CheckedBy");

                    b.Property<DateTime?>("CheckedTime");

                    b.Property<string>("Comment");

                    b.Property<string>("EditedBy");

                    b.Property<DateTime?>("EditedTime");

                    b.Property<string>("Key");

                    b.Property<string>("OriginalText")
                        .IsRequired();

                    b.Property<string>("TranslatedBy");

                    b.Property<string>("TranslatedText");

                    b.Property<DateTime?>("TranslatedTime");

                    b.Property<long>("VersionId");

                    b.HasKey("Id");

                    b.HasIndex("VersionId");

                    b.ToTable("Translations");
                });

            modelBuilder.Entity("Trs.Data.Entities.TrnVersion", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("CreatedOn");

                    b.Property<string>("Description");

                    b.Property<DateTime?>("EndedOn");

                    b.Property<DateTime?>("StartedOn");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200);

                    b.HasKey("Id");

                    b.ToTable("TrnVersion");
                });

            modelBuilder.Entity("Trs.Data.Entities.Translation", b =>
                {
                    b.HasOne("Trs.Data.Entities.TrnVersion", "TrnVersion")
                        .WithMany("Translations")
                        .HasForeignKey("VersionId")
                        .OnDelete(DeleteBehavior.Cascade);
                });
#pragma warning restore 612, 618
        }
    }
}
